### ISSUE TITLE
could not create 'monotonic_align\core.cp310-win_amd64.pyd': No such file or directory

### ISSUE THREAD

**Issue by sj112538** [Li-Kira/VITS_WebUI#1]
running build_ext
error: could not create 'monotonic_align\core.cp310-win_amd64.pyd': No such file or directory
这个报错是为啥

**Comment by Li-Kira** [comment]
由于一些cmake历史遗留问题，在**Visual Studio Installer**中安装**MSVC**依赖需要先删除Python中已经安装的包（如果有）。推荐clone本项目到Google Colab中，可以避免很多环境相关的问题。
